[project]
name = 'abc'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.constant-tradables]
path = 'contracts/constant-tradables.clar'
clarity_version = 1
epoch = 2.05

[contracts.market]
path = 'contracts/market.clar'
clarity_version = 1
epoch = 2.05

[contracts.monsters]
path = 'contracts/monsters.clar'
clarity_version = 3
epoch = 3.0

[contracts.tool-mega]
path = 'contracts/tool-mega.clar'
clarity_version = 2
epoch = 2.5

[contracts.tradables-trait]
path = 'contracts/tradables-trait.clar'
clarity_version = 1
epoch = 2.05
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
